---
apiVersion: v1
kind: Service
metadata:
  name: mailhog
  labels:
    app: fleet
    component: mailhog
spec:
  type: NodePort
  ports:
  - name: smtp
    port: 1025
    nodePort: 31025
  - name: http
    port: 8025
    nodePort: 32025
  selector:
    component: mailhog
